const mongoose = require("mongoose");
const { User, Contact, VideoGame } = require("../models");
const bcrypt = require("bcrypt");
const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../.env") });

//get mongoose connection object
mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/" + process.env.DB_NAME,
    {
        useNewUrlParser: true,
        useUnifiedTopology: true,
        // useCreateIndex: true,
        // useFindAndModify: false,
    }
);

//hash password function for seed passwords
const hashPassword = (password) => {
    return bcrypt.hashSync(password, 10);
};

//data object to be inserted in to db
const userSeed = [
    {
        email: "davidtunnell9@gmail.com",
        password: hashPassword(process.env.ADMIN_PW),
        firstName: "David",
        lastName: "Tunnell",
        token: "",
    },
];

const contactSeed = [
    {
        createdAt: Date.now(),
        name: "Testy McTesterson",
        email: "fake@email.com",
        phone: "123-456-7890",
        message: "First message in the database.",
    },
];

const vgSeed = [
    {
        createdAt: Date.now(),
        title: "The Legend of Zelda",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "The Legend of Zelda - A Link to the Past",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Soul Blazer",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Mega Man 2",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Mega Man 3",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Super Mario World",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: World at War",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Black Ops 2",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Diablo",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy VII",
        difficulty: "",
        date: null,
        notes: "PS1",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "The Legend of Zelda: The Wind Waker",
        difficulty: "",
        date: null,
        notes: "Gamecube",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Resident Evil",
        difficulty: "",
        date: null,
        notes: "Gamecube",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Street Fighter II",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Rome: Total War",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Chip 'n Dale Rescue Rangers",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Little Nemo: The Dream Master",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Duck Tales",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Fable",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Halflife 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Halflife 2: Episode 1",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Portal",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Prey",
        difficulty: "",
        date: null,
        notes: "2006",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Halflife 2: Episode 2",
        difficulty: "",
        date: null,
        notes: "2006",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Clive Barker's Jericho",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Modern Warfare",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Gun",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Quake 4",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Rainbow 6: Vegas",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty 2",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Gears of War",
        difficulty: "Normal",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Half-life",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Battlefield: Bad Company",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Crysis",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Crysis: Warhead",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Killzone 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Black Ops",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Modern Warfare 2",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Medal of Honor",
        difficulty: "",
        date: null,
        notes: "2010",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Crysis 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Battlefield 3",
        difficulty: "",
        date: null,
        notes: "I thought I beat this on hard but didn't write it down.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Modern Warfare 3",
        difficulty: "",
        date: null,
        notes: "I thought I beat this on hardened but didn't write it down.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Crysis 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Doom",
        difficulty: "",
        date: null,
        notes: "2016",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Hearthstone: Naxxrammas",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Hearthstone: Blackrock Mountain",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Hearthstone: League of Explorers",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Resistance: Fall of Man",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "God of War II",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Gears of War",
        difficulty: "Insane",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Guild Wars: Nightfall",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Guild Wars: Prophecies",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Bioshock",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Halo",
        difficulty: "",
        date: null,
        notes: "I recall beating this on legendary but didn't write it down.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Halo 2",
        difficulty: "",
        date: null,
        notes: "I recall beating this on legendary but didn't write it down.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Halo 3",
        difficulty: "Heroic",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Halo 3",
        difficulty: "Legendary",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Mass Effect",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "The Elder Scrolls IV: Oblivion",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Secret of Mana",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Eternal Sonata",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy III",
        difficulty: "",
        date: null,
        notes: "SNES - 6 in Japan",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "The Elder Scrolls IV: Oblivion: The Shivering Isles",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Perfect Dark Zero",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Uncharted: Drake's Fortune",
        difficulty: "",
        date: null,
        notes: "I recall beating this on hard but didn't write it down.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Army of Two",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Kane and Lynch: Dead Men",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Beautiful Katamari",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Unreal Tournament 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Shadow of Colossus",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Diablo II",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Diablo II: Lord of Destruction",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Lost Oddessy",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Super Mario Bros 3",
        difficulty: "",
        date: null,
        notes: "SNES/All Stars",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Dead Space",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Grand Theft Auto 4",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Fallout 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Little Big Planet",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Prince of Persia",
        difficulty: "",
        date: null,
        notes: "2008",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Neverwinter Nights 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Sonic the Hedgehog 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy VIII",
        difficulty: "",
        date: null,
        notes: "PS1",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "World of Warcraft",
        difficulty: "",
        date: null,
        notes: "Level 60",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "World of Warcraft: The Burning Crusade",
        difficulty: "",
        date: null,
        notes: "TBC Level 70",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dragon Age: Origins",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "World of Warcraft: Wrath of the Lich King",
        difficulty: "",
        date: null,
        notes: "WOTLK Level 80",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Mass Effect 2",
        difficulty: "",
        date: null,
        notes: "I recall beating this on hard but didn't write it down.",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "World of Warcraft: Cataclysm",
        difficulty: "",
        date: null,
        notes: "Cataclysm Level 85",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Enslaved: Odyssey of the West",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Alan Wake",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Portal 2",
        difficulty: "",
        date: null,
        notes: "I need to play this again. I don't remember it well and it's many people's GOAT.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dragon Age 2",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Deus Ex: Human Revolution",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Uncharted 2: Among Thieves",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Gears of War",
        difficulty: "Hardcore",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Elder Scrolls V: Skyrim",
        difficulty: "",
        date: null,
        notes: "Bowl Hunter 3D",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Killzone 3",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Mass Effect 3",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Diablo 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Magicka",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Halo 4",
        difficulty: "Legendary",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Uncharted 3",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Doom 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Bioshock: Infinity",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "The Last of Us",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Tomb Raider",
        difficulty: "Hard",
        date: null,
        notes: "2013",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy 14: A Realm Reborn",
        difficulty: "",
        date: null,
        notes: "Level 50",
        rating: "Normal",
    },
];

//first delete data in database and then populate with seed data
setTimeout(function () {
    User.deleteMany({})
        .then(() => User.insertMany(userSeed))
        .then((data) => {
            console.log(
                data.length +
                    " " +
                    Object.keys({ userSeed })[0] +
                    " records inserted."
            );
        })
        .catch((err) => {
            console.error(err);
            process.exit(1);
        });
}, 1000);

setTimeout(function () {
    Contact.deleteMany({})
        .then(() => Contact.insertMany(contactSeed))
        .then((data) => {
            console.log(
                data.length +
                    " " +
                    Object.keys({ contactSeed })[0] +
                    " records inserted."
            );
        })
        .catch((err) => {
            console.error(err);
            process.exit(1);
        });
}, 1000);

setTimeout(function () {
    VideoGame.deleteMany({})
        .then(() => VideoGame.insertMany(vgSeed))
        .then((data) => {
            console.log(
                data.length +
                    " " +
                    Object.keys({ vgSeed })[0] +
                    " records inserted."
            );
            process.exit(0);
        })
        .catch((err) => {
            console.error(err);
            process.exit(1);
        });
}, 1000);
