const mongoose = require("mongoose");
const { User, Contact, VideoGame } = require("../models");
const bcrypt = require("bcrypt");
const path = require("path");
require("dotenv").config({ path: path.resolve(__dirname, "../.env") });

//get mongoose connection object
mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/" + process.env.DB_NAME,
    {
        useNewUrlParser: true,
        useUnifiedTopology: true,
        // useCreateIndex: true,
        // useFindAndModify: false,
    }
);

//hash password function for seed passwords
const hashPassword = (password) => {
    return bcrypt.hashSync(password, 10);
};

//data object to be inserted in to db
const userSeed = [
    {
        email: "davidtunnell9@gmail.com",
        password: hashPassword(process.env.ADMIN_PW),
        firstName: "David",
        lastName: "Tunnell",
        token: "",
    },
];

const contactSeed = [
    {
        createdAt: Date.now(),
        name: "Testy McTesterson",
        email: "fake@email.com",
        phone: "123-456-7890",
        message: "First message in the database.",
    },
];

const vgSeed = [
    {
        createdAt: Date.now(),
        title: "The Legend of Zelda",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "The Legend of Zelda - A Link to the Past",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Soul Blazer",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Mega Man 2",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Mega Man 3",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Super Mario World",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: World at War",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Black Ops 2",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Diablo",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy VII",
        difficulty: "",
        date: null,
        notes: "PS1",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "The Legend of Zelda: The Wind Waker",
        difficulty: "",
        date: null,
        notes: "Gamecube",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Resident Evil",
        difficulty: "",
        date: null,
        notes: "Gamecube",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Street Fighter II",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Rome: Total War",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Chip 'n Dale Rescue Rangers",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Little Nemo: The Dream Master",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Duck Tales",
        difficulty: "",
        date: null,
        notes: "NES",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Fable",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Halflife 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Halflife 2: Episode 1",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Portal",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Prey (2006)",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Halflife 2: Episode 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Clive Barker's Jericho",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Modern Warfare",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Gun",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Quake 4",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Rainbow 6: Vegas",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty 2",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Gears of War",
        difficulty: "Normal",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Half-life",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Battlefield: Bad Company",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Crysis",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Crysis: Warhead",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Killzone 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Black Ops",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Modern Warfare 2",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Medal of Honor",
        difficulty: "",
        date: null,
        notes: "2010",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Crysis 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Battlefield 3",
        difficulty: "",
        date: null,
        notes: "I thought I beat this on hard but didn't write it down.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Modern Warfare 3",
        difficulty: "",
        date: null,
        notes: "I thought I beat this on hardened but didn't write it down.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Crysis 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Doom (2016)",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Hearthstone: Naxxrammas",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Hearthstone: Blackrock Mountain",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Hearthstone: League of Explorers",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Resistance: Fall of Man",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "God of War II",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Gears of War",
        difficulty: "Insane",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Guild Wars: Nightfall",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Guild Wars: Prophecies",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Bioshock",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Halo",
        difficulty: "",
        date: null,
        notes: "I recall beating this on legendary but didn't write it down.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Halo 2",
        difficulty: "",
        date: null,
        notes: "I recall beating this on legendary but didn't write it down.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Halo 3",
        difficulty: "Heroic",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Halo 3",
        difficulty: "Legendary",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Mass Effect",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "The Elder Scrolls IV: Oblivion",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Secret of Mana",
        difficulty: "",
        date: null,
        notes: "SNES",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Eternal Sonata",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy III",
        difficulty: "",
        date: null,
        notes: "SNES - 6 in Japan",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "The Elder Scrolls IV: Oblivion: The Shivering Isles",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Perfect Dark Zero",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Uncharted: Drake's Fortune",
        difficulty: "",
        date: null,
        notes: "I recall beating this on hard but didn't write it down.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Army of Two",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Kane and Lynch: Dead Men",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Beautiful Katamari",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Unreal Tournament 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Shadow of Colossus",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Diablo II",
        difficulty: "",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Diablo II: Lord of Destruction",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Lost Oddessy",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Super Mario Bros 3",
        difficulty: "",
        date: null,
        notes: "SNES/All Stars",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Dead Space",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Fallout 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Little Big Planet",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Prince of Persia",
        difficulty: "",
        date: null,
        notes: "2008",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Neverwinter Nights 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Sonic the Hedgehog 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy VIII",
        difficulty: "",
        date: null,
        notes: "PS1",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "World of Warcraft",
        difficulty: "",
        date: null,
        notes: "Level 60",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "World of Warcraft: The Burning Crusade",
        difficulty: "",
        date: null,
        notes: "TBC Level 70",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dragon Age: Origins",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "World of Warcraft: Wrath of the Lich King",
        difficulty: "",
        date: null,
        notes: "WOTLK Level 80",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Mass Effect 2",
        difficulty: "",
        date: null,
        notes: "I recall beating this on hard but didn't write it down.",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "World of Warcraft: Cataclysm",
        difficulty: "",
        date: null,
        notes: "Cataclysm Level 85",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Enslaved: Odyssey of the West",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Alan Wake",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Portal 2",
        difficulty: "",
        date: null,
        notes: "I need to play this again. I don't remember it well and it's many people's GOAT.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dragon Age 2",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Deus Ex: Human Revolution",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Uncharted 2: Among Thieves",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Gears of War",
        difficulty: "Hardcore",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Elder Scrolls V: Skyrim",
        difficulty: "",
        date: null,
        notes: "Bowl Hunter 3D",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Killzone 3",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Mass Effect 3",
        difficulty: "",
        date: null,
        notes: "I thought I played this on hard.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Diablo 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Magicka",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Halo 4",
        difficulty: "Legendary",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Uncharted 3",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Doom 3",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Bioshock: Infinity",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "The Last of Us",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Tomb Raider",
        difficulty: "Hard",
        date: null,
        notes: "2013",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy 14: A Realm Reborn",
        difficulty: "",
        date: null,
        notes: "Level 50",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "League of Legends",
        difficulty: "",
        date: null,
        notes: "Level 30 x3 accounts (Used to be Max)",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Path of Exile",
        difficulty: "Normal",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Path of Exile",
        difficulty: "Cruel",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Path of Exile",
        difficulty: "Merciless",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Wolfenstein: The New Order",
        difficulty: "",
        date: null,
        notes: "I'm almost positive I beat it on hard but the difficulty wasn't written down.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy X",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dragon Age: Inquisition",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Grand Theft Auto 5",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Max the Curse of Brotherhood",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Ghosts",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Destiny",
        difficulty: "Hardened",
        date: null,
        notes: "Completed main storyline.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Advanced Warfare",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Farcry 4",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Limbo",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Rayman Legends",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Battlefield: Hardline",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Ori and the Blind Forest",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Shovel Knight",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Mega Man Legacy: Mega Man 1",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Destiny: The Taken King",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "The Witcher 3: Wild Hunt",
        difficulty: "",
        date: null,
        notes: "I'm almost positive I beat it on hard but the difficulty wasn't written down.",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "The Walking Dead: Episode 1",
        difficulty: "",
        date: null,
        notes: "Telltale Games",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "The Witcher 3: Heart of Stone",
        difficulty: "",
        date: null,
        notes: "Telltale Games",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Game of Thrones Episodes 1-6",
        difficulty: "",
        date: null,
        notes: "Telltale Games",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Fallout 4",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Wolfenstein: The Old Blood",
        difficulty: "",
        date: null,
        notes: "I'm almost positive I beat it on hard but the difficulty wasn't written down.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Black Ops 3",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Undertale",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Rise of the Tomb Raid",
        difficulty: "",
        date: null,
        notes: "I'm almost positive I beat it on hard but the difficulty wasn't written down.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dying Light",
        difficulty: "",
        date: null,
        notes: "I thought I beat this on hard too.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Tales of Zestiria",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Life is Strange",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Quantum Break",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Evoland 2",
        difficulty: "Hard",
        date: null,
        notes: "Very cool idea.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Uncharted 4",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Gears of War 2",
        difficulty: "Hardcore",
        date: null,
        notes: "So much great multiplayer with friends.",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Gears of War 3",
        difficulty: "Hardcore",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Rogue Galaxy",
        difficulty: "",
        date: null,
        notes: "PS2 Version",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Heavy Rain",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Brothers: A Tale of Two Sons",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "The Order: 1886",
        difficulty: "",
        date: null,
        notes: "I thought I beat this on hard too.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dishonored",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dishonored: The Brigmore Witches",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dishonored: Knife of Dunwall",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Battlefield 1",
        difficulty: "Hard",
        date: null,
        notes: "I'm almost positive I beat it on hard but the difficulty wasn't written down.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Red Dead Redemption",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy XV",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Unravel",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Neverwinter: Elemental Evil",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Neverwinter: Sharandar",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Neverwinter: Dread Ring",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Neverwinter: The Maze Engine",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Modern Warfare Remastered",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Infinite Warfare",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Titanfall 2",
        difficulty: "",
        date: null,
        notes: "I'm almost positive I beat it on hard but the difficulty wasn't written down. I need to play this campaign again.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Until Dawn",
        difficulty: "",
        date: null,
        notes: "Only the girl from Heros lived.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dishonored 2",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Horizon: New Dawn",
        difficulty: "",
        date: null,
        notes: "I thought I beat this on hard too.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Resident Evil 7: Biohazard",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Mass Effect: Andromeda",
        difficulty: "Hardcore",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Sniper Elite 4",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Prey (2017)",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Inside",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Zelda: Breath of the Wild",
        difficulty: "",
        date: null,
        notes: "82 shrines and full ancient armor",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Firewatch",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Axiom Verge",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy XII: The Zodiac Age",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Killzone : Shadow Fall",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Shadow Complex: Remastered",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Wolfenstein II: The New Colossus",
        difficulty: "Do or Die!",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Deus Ex: Mankind Divided",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Uncharted: Lost Legacy",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: World War 2",
        difficulty: "Hardened",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Watch Dogs 2",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy IX",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Star Wars Battlefront 2 (2017)",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Super Mario Odyssey",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Iconoclasts",
        difficulty: "Harder",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Farcry 5",
        difficulty: "",
        date: null,
        notes: "I thought I beat this on hard too.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "God of War (2018)",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "All Time Great",
    },
    {
        createdAt: Date.now(),
        title: "Nier: Automata",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Gears of War 4",
        difficulty: "Hardcore",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Vampyr",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Detroit: Become Human",
        difficulty: "",
        date: null,
        notes: "My ending sucked.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Steamworld Dig 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty Black Ops 3",
        difficulty: "Veteran",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "The Last of Us: Remastered",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "The Last of Us: Remastered - Left Behind",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Destiny 2",
        difficulty: "",
        date: null,
        notes: "Beat main storyline.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Destiny 2: Curse of Osiris",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Destiny 2: Warmind",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Sonic Mania",
        difficulty: "",
        date: null,
        notes: "with Knuckles",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Destiny 2: Forsaken",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Cavestory+",
        difficulty: "",
        date: null,
        notes: "With Joyce - 1st game we beat together",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Spiderman (2018)",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Lovers in a Dangerous Spacetime",
        difficulty: "",
        date: null,
        notes: "With Joyce",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Roundabout",
        difficulty: "",
        date: "12/01/2018",
        notes: "Game was ridiculous lol",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Trine 2",
        difficulty: "Hard",
        date: null,
        notes: "With Joyce",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Trine 2: Goblin Invasion",
        difficulty: "Hard",
        date: null,
        notes: "With Joyce",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Ninja Gaiden",
        difficulty: "",
        date: "12/31/2018",
        notes: "NES Classic System (2016)",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Red Dead Redemption 2",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dragon Quest XI",
        difficulty: "",
        date: "02/09/2019",
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Trine 3",
        difficulty: "",
        date: "02/17/2019",
        notes: ":) - With Joyce",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Battlefield 5",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Assassins Creed: Odyssey",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Metro Exodus",
        difficulty: "",
        date: null,
        notes: "I thought I beat this on hardcore too.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Bulletstorm: Full Clip Edition",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "House of the Dead: Scarlet Dawn - Arcade",
        difficulty: "",
        date: null,
        notes: "With Joyce @ Dave and Busters /w a Groupon",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Warcraft 3: Reign of Chaos",
        difficulty: "",
        date: null,
        notes: "Finally beat it in preparation for WoW Classic.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Secret of Mana: Remake (2017)",
        difficulty: "",
        date: null,
        notes: "With Joyce",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Overcooked",
        difficulty: "",
        date: null,
        notes: "With Joyce - Full 3 Stars",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Overcooked: The Lost Morsel",
        difficulty: "",
        date: null,
        notes: "With Joyce - Full 3 Stars",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Overcooked: The Festive Seasoning",
        difficulty: "",
        date: null,
        notes: "With Joyce - Full 3 Stars",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Overcooked 2",
        difficulty: "",
        date: null,
        notes: "With Joyce - Full 3 Stars",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Super Mario Bros U Deluxe",
        difficulty: "",
        date: null,
        notes: "With Joyce",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "What Remains of Edith Finch",
        difficulty: "",
        date: null,
        notes: "With Joyce",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Warcraft 3: The Frozen Throne",
        difficulty: "",
        date: null,
        notes: "Also to prep for WoW Classic. Great storyline.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "A Way Out",
        difficulty: "",
        date: null,
        notes: "With Joyce",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "The Outer Worlds",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Modern Warfare (2019)",
        difficulty: "Veteran",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Star Wars Jedi: Fallen Order",
        difficulty: "Jedi Master / Hard",
        date: null,
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Unraveled Two",
        difficulty: "Jedi Master / Hard",
        date: null,
        notes: "With Joyce - 1-12 challenges also",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Mario + Rabbids: Kingdom Battle",
        difficulty: "",
        date: null,
        notes: "No extra life / easy mode ever",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Control (2019)",
        difficulty: "",
        date: "12/28/2019",
        notes: "No difficulty option available",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Kingdom Come: Deliverance - A Woman's Lot",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Kingdom Come: Deliverance",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "A Plague Tale: Innocence",
        difficulty: "",
        date: "02/02/2020",
        notes: "No difficulty option available",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Valley (2016)",
        difficulty: "",
        date: "02/04/2020",
        notes: "No difficulty option available",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Trine 1: Enhanced Edition",
        difficulty: "Hard/Unlimited",
        date: "02/10/2020",
        notes: "With Joyce",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "The Chosen RPG",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Pikuniku",
        difficulty: "",
        date: null,
        notes: "Co-Op Campaign - With Joyce!",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Pikuniku",
        difficulty: "",
        date: null,
        notes: "Main Single Player Campaign",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Rage 2",
        difficulty: "Hard",
        date: null,
        notes: "+ Worm Boss",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Dust: An Elysian Tail",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Grim Dawn",
        difficulty: "Veteran/Hard",
        date: null,
        notes: "With Joyce!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Doom Eternal",
        difficulty: "Ulta Violence/Hard",
        date: "04/18/2020",
        notes: "",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Final Fantasy 7: Remake",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Fallout: New Vegas",
        difficulty: "Hard",
        date: "06/08/2020",
        notes: "Someone will want to murder me for rating this normal.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Ryse: Son of Rome (PC)",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Evoland 1 (Classic)",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Hearthstone: Ashes of Outlands",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Black Mesa",
        difficulty: "Black Mesa Difficulty (Hard)",
        date: null,
        notes: "v1.0 release",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Hearthstone: Galakrond's Awakening",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Hearthstone: Karazhan",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "GuildWars 2",
        difficulty: "",
        date: null,
        notes: "With Joyce, level 80, Beat main story",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Celeste",
        difficulty: "",
        date: "09/05/2020",
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Ghost of Tsushima",
        difficulty: "Hard",
        date: null,
        notes: "Finished all companion story lines, got most armors",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Super Mario Galaxy (Super Mario 3D All-Stars)",
        difficulty: "",
        date: "11/08/2020",
        notes: "73 stars",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Xenoblade Chronicles: Definitive Edition",
        difficulty: "",
        date: null,
        notes: "Never downgraded difficulty, Lvl 83, ~100 hours ",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Cyberpunk 2077",
        difficulty: "Hard",
        date: null,
        notes: "Did corpo ending and both of Panam's",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Ori and the Will of the Wisps",
        difficulty: "",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Duty: Cold War",
        difficulty: "Veteran",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Rocket Birds: Hardboiled Chicken",
        difficulty: "",
        date: null,
        notes: "With Joyce!",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "ReCore: Definitive Edition",
        difficulty: "",
        date: null,
        notes: "51+ prismatic cores",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "The Legend of Zelda: Link's Awakening (Switch)",
        difficulty: "",
        date: "06/10/2021",
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Mirror's Edge: Catalyst",
        difficulty: "",
        date: "06/16/2021",
        notes: "Almost incredible rating.",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Call of Juarez: Gunslinger",
        difficulty: "Hard",
        date: null,
        notes: "",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Albion Online",
        difficulty: "",
        date: null,
        notes: "500+ hours, maxed weapons and armor, 100 arena wins, 100 farming and much more.. still gonna come back to it",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Chrono Trigger",
        difficulty: "",
        date: "09/25/2021",
        notes: "SNES9x Emulator, beat all end game side quests, killed magus",
        rating: "Incredible",
    },
    {
        createdAt: Date.now(),
        title: "Chrono Cross",
        difficulty: "",
        date: "10/16/2021",
        notes: "RetroArch Beetle PS1 Emulator",
        rating: "Normal",
    },
    {
        createdAt: Date.now(),
        title: "Code Vein",
        difficulty: "",
        date: "11/05/2021",
        notes: "Beat all depths, 100% all maps, never used multiplayer help",
        rating: "Incredible",
    },
];

//first delete data in database and then populate with seed data
setTimeout(function () {
    User.deleteMany({})
        .then(() => User.insertMany(userSeed))
        .then((data) => {
            console.log(
                data.length +
                    " " +
                    Object.keys({ userSeed })[0] +
                    " records inserted."
            );
        })
        .catch((err) => {
            console.error(err);
            process.exit(1);
        });
}, 1000);

setTimeout(function () {
    Contact.deleteMany({})
        .then(() => Contact.insertMany(contactSeed))
        .then((data) => {
            console.log(
                data.length +
                    " " +
                    Object.keys({ contactSeed })[0] +
                    " records inserted."
            );
        })
        .catch((err) => {
            console.error(err);
            process.exit(1);
        });
}, 1000);

setTimeout(function () {
    VideoGame.deleteMany({})
        .then(() => VideoGame.insertMany(vgSeed))
        .then((data) => {
            console.log(
                data.length +
                    " " +
                    Object.keys({ vgSeed })[0] +
                    " records inserted."
            );
            process.exit(0);
        })
        .catch((err) => {
            console.error(err);
            process.exit(1);
        });
}, 1000);
